# Project: Ë³Ðò±í
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Ë³Ðò±í/Ë³Ðò±í.o
LINKOBJ  = Ë³Ðò±í/Ë³Ðò±í.o
LIBS     = -L"D:/software/program/C++/Dev-Cpp/MinGW64/lib" -L"D:/software/program/C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/software/program/C++/Dev-Cpp/MinGW64/include" -I"D:/software/program/C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/software/program/C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/software/program/C++/Dev-Cpp/MinGW64/include" -I"D:/software/program/C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/software/program/C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/software/program/C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Ë³Ðò±í.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

Ë³Ðò±í/Ë³Ðò±í.o: Ë³Ðò±í/Ë³Ðò±í.c
	$(CC) -c Ë³Ðò±í/Ë³Ðò±í.c -o Ë³Ðò±í/Ë³Ðò±í.o $(CFLAGS)
